name: Deploy

on:
  schedule:
    - cron: '0 22 * * *' # 毎日 07:00(JST)

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
